### ISSUE TITLE
Trying to set a tensor of shape torch.Size([1024]) in "class_embedding" (which has shape torch.Size([4096])), this look incorrect

### ISSUE THREAD

**Issue by Sandwichzhao** [Ucas-HaoranWei/Vary#53]
执行demo时，报错了
 python vary/demo/run_qwen_vary.py  --model-name /home/XX/Vary/Vary-master/vary/model/path/vary-llava80k/ --image-file OCR_PIC.png

 **cuda version 11.7 另外安装了 pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1**

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading checkpoint shards:  50%|████████████████████████████████████████████████████████████████████                                                                    | 1/2 [00:16<00:16, 16.82s/it]
Traceback (most recent call last):
  File "/home/itouchtv/zhao/Vary/Vary-master/vary/demo/run_qwen_vary.py", line 127, in <module>
    eval_model(args)
  File "/home/itouchtv/zhao/Vary/Vary-master/vary/demo/run_qwen_vary.py", line 43, in eval_model
    model = varyQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', trust_remote_code=True)
  File "/home/itouchtv/.conda/envs/vary/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3091, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/itouchtv/.conda/envs/vary/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3471, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/itouchtv/.conda/envs/vary/lib/python3.10/site-packages/transformers/modeling_utils.py", line 736, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/itouchtv/.conda/envs/vary/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([1024]) in "class_embedding" (which has shape torch.Size([4096])), this look incorrect.

**Comment by Sandwichzhao** [comment]
模型文件路径加载错了

**Comment by zhangxyzte** [comment]
> 模型文件路径加载错了
您好，能具体说一下吗，我也遇到这个问题

**Comment by Sandwichzhao** [comment]
> /home/XX/Vary/Vary-master/vary/model/path/vary-llava80k/

1.联系作者WeiHaoran把Vary Weights文件从网盘下载放到 /home/XX/Vary/Vary-master/vary/model/path/vary-llava80k/
2.翻墙从huggingface下载https://huggingface.co/openai/clip-vit-large-patch14/tree/main，把文件下载到/cache/vit-large-patch14/
3.执行 python vary/demo/run_qwen_vary.py --model-name /home/XX/Vary/Vary-master/vary/model/path/vary-llava80k/ --image-file OCR_PIC.png

**Comment by zhangxyzte** [comment]
嗯明白了，太感谢了
