### ISSUE TITLE
运行run_qwen_vary.py报错/cache/vit-large-patch14/相关，请指教！

### ISSUE THREAD

**Issue by DongyangLiu** [Ucas-HaoranWei/Vary#72]
MacBook-Pro Vary-master % python /Users/a58/Desktop/Vary/Vary/Vary-master/vary/demo/run_qwen_vary.py --model-name /Users/a58/Desktop/Vary/Vary/Vary-master/vary/model/path/clip-vit-large-patch14 --image-file /Users/a58/Desktop/Vary/Vary/Vary-master/an/image/11111.png
/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type clip to instantiate a model of type vary. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/cache/vit-large-patch14/'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/Desktop/Vary/Vary/Vary-master/vary/demo/run_qwen_vary.py", line 127, in <module>
    eval_model(args)
  File "/Users/a58/Desktop/Vary/Vary/Vary-master/vary/demo/run_qwen_vary.py", line 43, in eval_model
    model = varyQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', trust_remote_code=True)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2876, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/vary/model/vary_qwen_vary.py", line 238, in __init__
    self.transformer = varyQwenModel(config)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/vary/model/vary_qwen_vary.py", line 48, in __init__
    self.vision_tower = CLIPVisionModel.from_pretrained('/cache/vit-large-patch14/')
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 238, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/vary/lib/python3.10/site-packages/transformers/configuration_utils.py", line 696, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of '/cache/vit-large-patch14/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/cache/vit-large-patch14/' is the correct path to a directory containing a config.json file

**Comment by Ucas-HaoranWei** [comment]
你需要在huggingface上下载clip-vit-l，然后把这个路径改为你下载的本地路径

**Comment by hotwa** [comment]
路径错误，在安装源码之前就应该修改
vary/Vary-master/vary/demo/run_qwen_vary.py
vary/Vary-master/vary/model/vary_qwen_vary.py
这里面`/cache/vit-large-patch14/`的位置，然后再执行pip install e .安装，其实这里设置一个环境变量会更好，需要调整源码，作者懒得改

**Comment by hotwa** [comment]
sed -i 's|/cache/vit-large-patch14/|/path/to/your/downloaded/weights/|g' vary/Vary-master/vary/demo/run_qwen_vary.py
sed -i 's|/cache/vit-large-patch14/|/path/to/your/downloaded/weights/|g' vary/Vary-master/vary/model/vary_qwen_vary.py
请确保将 /path/to/your/downloaded/weights/ 替换为你的实际权重文件所在的路径。此命令使用 sed 的 -i 选项来直接修改文件内容，s|查找的文本|替换为的文本|g 是 sed 的替换指令，其中 g 表示全局替换（即替换所有匹配项）。

在运行这些命令之后，你的文件中所有的 /cache/vit-large-patch14/ 应该都被替换为了新的权重文件路径。然后，你就可以继续安装过程了。
