### ISSUE TITLE
The Vary-Tiny pretrain model can not be inferenced

### ISSUE THREAD

**Issue by lucasjinreal** [Ucas-HaoranWei/Vary#82]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/Vary/run_opt.py", line 111, in <module>
    eval_model(args)
  File "/Vary/run_opt.py", line 80, in eval_model
    output_ids = model.generate(
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/transformers/generation/utils.py", line 2734, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

Looks like it doesn do any meanful output for vary -tiny?

I suppose it should do OCR ability as it trained on millions of arxiv articles images.

**Comment by Ucas-HaoranWei** [comment]
This is because the version of the inference code is wrong, I will release the correct version today.

**Comment by Ucas-HaoranWei** [comment]
I upload the run_open_with_text.py in /demo/, please try it.

**Comment by zhyj3038** [comment]
frankly speaking, I found  lot of erros in the train code., and only the inference code can run.  
the open source of your code always mislead other people。

**Comment by lucasjinreal** [comment]
HI

"use_im_start_end" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUndefinedVariable)

**Comment by lucasjinreal** [comment]
Still same error:

![image](https://github.com/Ucas-HaoranWei/Vary/assets/21303438/ed3c73c3-ecf1-47e4-bae2-45a172edf60b)

**Comment by lucasjinreal** [comment]
@Ucas-HaoranWei  Hi, what the error previously?

BTW, except for the `Provide the OCR results of this image.` Does other intruct like `read this` , `texts on image`, `this is what` etc, can work on opt model?

**Comment by shuiqingliu** [comment]
<img width="1862" alt="image" src="https://github.com/Ucas-HaoranWei/Vary/assets/4103971/c0f601e9-bd5e-4b70-beae-6123327cdd2b">
When I use `run_open_with_text` the output is garbled as shown in the picture above.What could be the possible reason for this?

**Comment by Ucas-HaoranWei** [comment]
You need the new Vary-master/vary/model/vary_opt.py

**Comment by shuiqingliu** [comment]
> You need the new Vary-master/vary/model/vary_opt.py

same error
test image:
![output_issue2_0](https://github.com/Ucas-HaoranWei/Vary/assets/4103971/b1fb8610-c8fb-4dd6-8a7c-6216b6e74f37)

**Comment by lucasjinreal** [comment]
I think this is normal.

My guess is the pretraining data in vary-opt has unicode characters, this might happen if the pdf are not decode properly, mostly because of it's quaility.

I have tested on some un-doc image, it hardly to produce OCR result. So that the opt itself has some limitations.

**Comment by Ucas-HaoranWei** [comment]
The vary-opt can not handle the formulas because we do not use such data, but the pure texts for both Chinese and English are OK.
The input:
![arxiv-1](https://github.com/Ucas-HaoranWei/Vary/assets/50487563/b09d44e1-0ba0-4df4-9b9b-ec35b2334d8d)
The output:
![image](https://github.com/Ucas-HaoranWei/Vary/assets/50487563/644302ad-acf5-4772-9221-46377c17f96c)

I guess you need to verify the transformers-version and best to rebuild the Vary.

**Comment by shuiqingliu** [comment]
> The vary-opt can not handle the formulas because we do not use such data, but the pure texts for both Chinese and English are OK. The input: ![arxiv-1](https://private-user-images.githubusercontent.com/50487563/314401348-b09d44e1-0ba0-4df4-9b9b-ec35b2334d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTkyMDMsIm5iZiI6MTcxMDkxODkwMywicGF0aCI6Ii81MDQ4NzU2My8zMTQ0MDEzNDgtYjA5ZDQ0ZTEtMGJhMC00ZGY0LTliOWItZWMzNWIyMzM0ZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzE2NzY5OGEwMDJjZmJiOWI2ODg3M2MzMmU4NDMzNzI3OTI5ODMwOTk4YzYxOWVjMzRmYTViMzFlM2RiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jIuveAeVTw8ZUq3RcdMzvIPQCL_GB7273KKxVFZuQMg) The output: ![image](https://private-user-images.githubusercontent.com/50487563/314401436-644302ad-acf5-4772-9221-46377c17f96c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTkyMDMsIm5iZiI6MTcxMDkxODkwMywicGF0aCI6Ii81MDQ4NzU2My8zMTQ0MDE0MzYtNjQ0MzAyYWQtYWNmNS00NzcyLTkyMjEtNDYzNzdjMTdmOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZGM3ZjUyMDJkODMxZGY5ZDZhZGZkM2Q0NDFiNjI5YTgwOWVhNTE3YTA5MjZjMDQ3ZmRhM2NjNDQ0MTZhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PdSrTIfRQFvECd_9k_Xqqs9CLaRN93yPfB80F__ilqw)
> 
> I guess you need to verify the transformers-version and best to rebuild the Vary.

Thank you for your attempt and hints @Ucas-HaoranWei

**Comment by lucasjinreal** [comment]
![image](https://github.com/Ucas-HaoranWei/Vary/assets/21303438/f069689b-d0fb-4a78-acb5-24d93f70ca1b)
![image](https://github.com/Ucas-HaoranWei/Vary/assets/21303438/de2e1edd-aa2e-4d47-baf9-6ea2f22b0997)
\

why still got unexpected result/

**Comment by lucasjinreal** [comment]
transformers 4.39 can not get right result, why?

**Comment by Ucas-HaoranWei** [comment]
Yes, after my testing, currently Vary-opt only can output the correct result based on transformers 4.32.1. I have tried 4.37.2 but cannot output the correct result. This may be because my code did not adapt to the new version of transformers. If I have free time recently, I will solve this problem.

**Comment by white2018** [comment]
![image](https://github.com/Ucas-HaoranWei/Vary/assets/26728432/fb4b0015-37c4-43ea-9bd6-a306624a9b03)
图片推理是乱码，模型加载时出现上面情况，模型地址：https://huggingface.co/HaoranWei/Vary-tiny-opt125M/tree/main
@Ucas-HaoranWei 请问乱码和用错模型有关吗？
